name: cyaim_websocket_client
description: WebSocket client for Cyaim.WebSocketServer with automatic endpoint discovery
version: 1.0.0
homepage: https://github.com/cyaim/websocket-server

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  json_annotation: ^4.8.0
  msgpack_dart: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

